import type { DebtItem } from '@/features/debts/model/debts.types'

export const debtItems: DebtItem[] = [
  {
    id: 'd1',
    name: 'Vay mua xe',
    debtType: 'bank_loan',
    lenderType: 'bank',
    lenderName: 'VPBank',
    originalAmount: '120M',
    outstandingAmount: '84M',
    currency: 'VND',
    borrowedAt: '2026-03-12',
    expectedFinalDueDate: '2028-03-12',
    status: 'active',
    ownerMemberId: 'm1',
    ownerName: 'Minh',
    receivedToAssetId: 'a2',
    receivedToAssetName: 'VCB chung',
    paymentFrequency: 'monthly',
    fixedPaymentAmount: '8,5M',
    interestSummary: '9.2%/năm · reducing balance',
    note: 'Khoản vay chính để mua xe đi làm và đưa đón con.',
  },
  {
    id: 'd2',
    name: 'Mượn mẹ để sửa nhà',
    debtType: 'family_loan',
    lenderType: 'family',
    lenderName: 'Mẹ',
    originalAmount: '40M',
    outstandingAmount: '18M',
    currency: 'VND',
    borrowedAt: '2026-01-18',
    status: 'active',
    ownerMemberId: 'm2',
    ownerName: 'An',
    receivedToAssetId: 'a3',
    receivedToAssetName: 'Techcombank',
    paymentFrequency: 'none',
    note: 'Trả linh hoạt khi có tiền dư, không tính lãi.',
  },
  {
    id: 'd3',
    name: 'Thẻ tín dụng tháng trước',
    debtType: 'credit_card',
    lenderType: 'bank',
    lenderName: 'ACB',
    originalAmount: '12,8M',
    outstandingAmount: '12,8M',
    currency: 'VND',
    borrowedAt: '2026-06-25',
    expectedFinalDueDate: '2026-07-20',
    status: 'overdue',
    ownerMemberId: 'm1',
    ownerName: 'Minh',
    receivedToAssetName: 'Chi tiêu thẻ',
    paymentFrequency: 'monthly',
    fixedPaymentAmount: '12,8M',
    interestSummary: 'Tạm tính theo sao kê nếu quá hạn',
    note: 'Cần chốt nguồn trả trong tuần này.',
  },
]
